[package]
name = "axwatchdog"
version = "0.1.0"
edition = "2024"
authors = ["ZhiXian Luo <luozhixian@kylinos.cn>"]
license = "Apache-2.0"


[dependencies]
axconfig.workspace = true
axipi.workspace = true
axlog.workspace = true
spin.workspace = true

lazy_static = { version = "1.5", features = ["spin_no_std"] }
axplat = "0.2"
axcpu = "0.2"