[package]
name = "axwatchdog"
version = "0.1.0"
edition = "2024"
authors = ["ZhiXian Luo <luozhixian@kylinos.cn>"]
license = "Apache-2.0"
description = "Watchdog timer with NMI support for embedded systems"
keywords = ["watchdog", "nmi", "embedded", "no_std"]
categories = ["no-std", "embedded", "hardware-support"]

[features]
default = []
sdei = ["dep:aarch64-sdei"]
pmu = ["dep:aarch64-pmuv3"]
log = ["dep:log"]
alloc = []

[dependencies]
aarch64-sdei = { path = "../aarch64-sdei", optional = true }
aarch64-pmuv3 = { path = "../aarch64-pmu", optional = true }
log = { version = "0.4", optional = true }